"""second

Revision ID: c532a3f8f78b
Revises: 3f9135e2417e
Create Date: 2025-03-05 20:11:53.744369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c532a3f8f78b'
down_revision: Union[str, None] = '3f9135e2417e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('additional_educational_program_type', sa.String(), nullable=True))
    op.add_column('assignment', sa.Column('reinstatement', sa.Boolean(), nullable=False))
    op.add_column('assignment', sa.Column('country', sa.String(), nullable=False))
    op.add_column('assignment', sa.Column('region', sa.String(), nullable=False))
    op.add_column('assignment', sa.Column('city', sa.String(), nullable=False))
    op.drop_column('listener', 'city')
    op.drop_column('listener', 'country')
    op.drop_column('listener', 'region')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listener', sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('listener', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('listener', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('assignment', 'city')
    op.drop_column('assignment', 'region')
    op.drop_column('assignment', 'country')
    op.drop_column('assignment', 'reinstatement')
    op.drop_column('assignment', 'additional_educational_program_type')
    # ### end Alembic commands ###
