"""empty message

Revision ID: f03658c801af
Revises: c532a3f8f78b
Create Date: 2025-03-05 23:06:14.974328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f03658c801af'
down_revision: Union[str, None] = 'c532a3f8f78b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listener', sa.Column('birth_year', sa.Integer(), nullable=False))
    op.drop_column('listener', 'birth_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listener', sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('listener', 'birth_year')
    # ### end Alembic commands ###
